### ISSUE TITLE
Bug: Object directory in Linux

### ISSUE THREAD

**Issue by Softaasi** [AasiApina/AE2D#1]
`make` creates directory `srcobj` when it should create `src/obj`. Rule `src\obj` should have forward slash.

    $ make
    mkdir -p src\obj
    gcc src/AE_color.c -c -DAE_BUILD_DLL -fPIC -I./include -ansi -o src/obj/AE_color.o
    Assembler messages:
    Fatal error: can't create src/obj/AE_color.o: No such file or directory
    make: *** [Makefile:41: AE_color.o] Error 1

Also `make clean` tries to remove wrong directory.

    $ make clean
    rm obj/*
    rm: cannot remove 'obj/*': No such file or directory
    make: *** [Makefile:45: clean] Error 1

Tulipa testattua tämä Issues.

**Comment by AasiApina** [comment]
Fixed
